// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/notify_relay/v1/relay.proto

package notify_relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification represents a desktop notification
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	ReplacesId    uint32                 `protobuf:"varint,2,opt,name=replaces_id,json=replacesId,proto3" json:"replaces_id,omitempty"`
	AppIcon       string                 `protobuf:"bytes,3,opt,name=app_icon,json=appIcon,proto3" json:"app_icon,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Actions       []string               `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Hints         map[string]string      `protobuf:"bytes,7,rep,name=hints,proto3" json:"hints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpireTimeout int32                  `protobuf:"varint,8,opt,name=expire_timeout,json=expireTimeout,proto3" json:"expire_timeout,omitempty"`
	Wait          bool                   `protobuf:"varint,9,opt,name=wait,proto3" json:"wait,omitempty"`
	PrintId       bool                   `protobuf:"varint,10,opt,name=print_id,json=printId,proto3" json:"print_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Notification) GetReplacesId() uint32 {
	if x != nil {
		return x.ReplacesId
	}
	return 0
}

func (x *Notification) GetAppIcon() string {
	if x != nil {
		return x.AppIcon
	}
	return ""
}

func (x *Notification) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Notification) GetHints() map[string]string {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *Notification) GetExpireTimeout() int32 {
	if x != nil {
		return x.ExpireTimeout
	}
	return 0
}

func (x *Notification) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

func (x *Notification) GetPrintId() bool {
	if x != nil {
		return x.PrintId
	}
	return false
}

// NotificationResponse is returned after sending a notification
type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Reason        uint32                 `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ActionKey     string                 `protobuf:"bytes,4,opt,name=action_key,json=actionKey,proto3" json:"action_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NotificationResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *NotificationResponse) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *NotificationResponse) GetActionKey() string {
	if x != nil {
		return x.ActionKey
	}
	return ""
}

// CloseRequest is used to close a notification
type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *CloseRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// CloseResponse confirms a notification was closed
type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *CloseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// CapabilitiesRequest asks for server capabilities
type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

// CapabilitiesResponse lists what the server supports
type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilitiesResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ServerInfoRequest asks for server information
type ServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

// ServerInfoResponse provides server details
type ServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Spec          string                 `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *ServerInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfoResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *ServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfoResponse) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

// HealthRequest is a simple health check
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{8}
}

// HealthResponse confirms the server is healthy
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// LockStateUpdate is sent by clients to report their lock state
type LockStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IsLocked      bool                   `protobuf:"varint,2,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockStateUpdate) Reset() {
	*x = LockStateUpdate{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockStateUpdate) ProtoMessage() {}

func (x *LockStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockStateUpdate.ProtoReflect.Descriptor instead.
func (*LockStateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{10}
}

func (x *LockStateUpdate) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *LockStateUpdate) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *LockStateUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthPing is a keepalive message from client to server
type HealthPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthPing) Reset() {
	*x = HealthPing{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthPing) ProtoMessage() {}

func (x *HealthPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthPing.ProtoReflect.Descriptor instead.
func (*HealthPing) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{11}
}

func (x *HealthPing) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthPong is a response to HealthPing
type HealthPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthPong) Reset() {
	*x = HealthPong{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthPong) ProtoMessage() {}

func (x *HealthPong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthPong.ProtoReflect.Descriptor instead.
func (*HealthPong) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{12}
}

func (x *HealthPong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ForwardedNotification is sent by server to client when forwarding
type ForwardedNotification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceHostname string                 `protobuf:"bytes,1,opt,name=source_hostname,json=sourceHostname,proto3" json:"source_hostname,omitempty"`
	Notification   *Notification          `protobuf:"bytes,2,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForwardedNotification) Reset() {
	*x = ForwardedNotification{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardedNotification) ProtoMessage() {}

func (x *ForwardedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardedNotification.ProtoReflect.Descriptor instead.
func (*ForwardedNotification) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{13}
}

func (x *ForwardedNotification) GetSourceHostname() string {
	if x != nil {
		return x.SourceHostname
	}
	return ""
}

func (x *ForwardedNotification) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

// ClientListUpdate informs clients about other connected clients
type ClientListUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*RemoteClient        `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientListUpdate) Reset() {
	*x = ClientListUpdate{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientListUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientListUpdate) ProtoMessage() {}

func (x *ClientListUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientListUpdate.ProtoReflect.Descriptor instead.
func (*ClientListUpdate) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{14}
}

func (x *ClientListUpdate) GetClients() []*RemoteClient {
	if x != nil {
		return x.Clients
	}
	return nil
}

// RemoteClient represents a connected remote client
type RemoteClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IsLocked      bool                   `protobuf:"varint,2,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	IsConnected   bool                   `protobuf:"varint,4,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteClient) Reset() {
	*x = RemoteClient{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteClient) ProtoMessage() {}

func (x *RemoteClient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteClient.ProtoReflect.Descriptor instead.
func (*RemoteClient) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{15}
}

func (x *RemoteClient) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RemoteClient) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *RemoteClient) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RemoteClient) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

// ClientMessage is sent from client to server via the Connect stream
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_LockState
	//	*ClientMessage_Ping
	//	*ClientMessage_Response
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{16}
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetLockState() *LockStateUpdate {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_LockState); ok {
			return x.LockState
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *HealthPing {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ClientMessage) GetResponse() *NotificationResponse {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_LockState struct {
	LockState *LockStateUpdate `protobuf:"bytes,1,opt,name=lock_state,json=lockState,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *HealthPing `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type ClientMessage_Response struct {
	Response *NotificationResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*ClientMessage_LockState) isClientMessage_Message() {}

func (*ClientMessage_Ping) isClientMessage_Message() {}

func (*ClientMessage_Response) isClientMessage_Message() {}

// ServerMessage is sent from server to client via the Connect stream
type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_Notification
	//	*ServerMessage_Pong
	//	*ServerMessage_ClientList
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notify_relay_v1_relay_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_notify_relay_v1_relay_proto_rawDescGZIP(), []int{17}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetNotification() *ForwardedNotification {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

func (x *ServerMessage) GetPong() *HealthPong {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ServerMessage) GetClientList() *ClientListUpdate {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ClientList); ok {
			return x.ClientList
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_Notification struct {
	Notification *ForwardedNotification `protobuf:"bytes,1,opt,name=notification,proto3,oneof"`
}

type ServerMessage_Pong struct {
	Pong *HealthPong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type ServerMessage_ClientList struct {
	ClientList *ClientListUpdate `protobuf:"bytes,3,opt,name=client_list,json=clientList,proto3,oneof"`
}

func (*ServerMessage_Notification) isServerMessage_Message() {}

func (*ServerMessage_Pong) isServerMessage_Message() {}

func (*ServerMessage_ClientList) isServerMessage_Message() {}

var File_proto_notify_relay_v1_relay_proto protoreflect.FileDescriptor

const file_proto_notify_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"!proto/notify_relay/v1/relay.proto\x12\x0fnotify_relay.v1\"\xfd\x02\n" +
	"\fNotification\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1f\n" +
	"\vreplaces_id\x18\x02 \x01(\rR\n" +
	"replacesId\x12\x19\n" +
	"\bapp_icon\x18\x03 \x01(\tR\aappIcon\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x18\n" +
	"\aactions\x18\x06 \x03(\tR\aactions\x12>\n" +
	"\x05hints\x18\a \x03(\v2(.notify_relay.v1.Notification.HintsEntryR\x05hints\x12%\n" +
	"\x0eexpire_timeout\x18\b \x01(\x05R\rexpireTimeout\x12\x12\n" +
	"\x04wait\x18\t \x01(\bR\x04wait\x12\x19\n" +
	"\bprint_id\x18\n" +
	" \x01(\bR\aprintId\x1a8\n" +
	"\n" +
	"HintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x14NotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\rR\x06reason\x12\x1d\n" +
	"\n" +
	"action_key\x18\x04 \x01(\tR\tactionKey\"\x1e\n" +
	"\fCloseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\")\n" +
	"\rCloseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13CapabilitiesRequest\":\n" +
	"\x14CapabilitiesResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"\x13\n" +
	"\x11ServerInfoRequest\"n\n" +
	"\x12ServerInfoResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x12\n" +
	"\x04spec\x18\x04 \x01(\tR\x04spec\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"h\n" +
	"\x0fLockStateUpdate\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1b\n" +
	"\tis_locked\x18\x02 \x01(\bR\bisLocked\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"*\n" +
	"\n" +
	"HealthPing\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"*\n" +
	"\n" +
	"HealthPong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x83\x01\n" +
	"\x15ForwardedNotification\x12'\n" +
	"\x0fsource_hostname\x18\x01 \x01(\tR\x0esourceHostname\x12A\n" +
	"\fnotification\x18\x02 \x01(\v2\x1d.notify_relay.v1.NotificationR\fnotification\"K\n" +
	"\x10ClientListUpdate\x127\n" +
	"\aclients\x18\x01 \x03(\v2\x1d.notify_relay.v1.RemoteClientR\aclients\"\x86\x01\n" +
	"\fRemoteClient\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1b\n" +
	"\tis_locked\x18\x02 \x01(\bR\bisLocked\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12!\n" +
	"\fis_connected\x18\x04 \x01(\bR\visConnected\"\xd5\x01\n" +
	"\rClientMessage\x12A\n" +
	"\n" +
	"lock_state\x18\x01 \x01(\v2 .notify_relay.v1.LockStateUpdateH\x00R\tlockState\x121\n" +
	"\x04ping\x18\x02 \x01(\v2\x1b.notify_relay.v1.HealthPingH\x00R\x04ping\x12C\n" +
	"\bresponse\x18\x03 \x01(\v2%.notify_relay.v1.NotificationResponseH\x00R\bresponseB\t\n" +
	"\amessage\"\xe1\x01\n" +
	"\rServerMessage\x12L\n" +
	"\fnotification\x18\x01 \x01(\v2&.notify_relay.v1.ForwardedNotificationH\x00R\fnotification\x121\n" +
	"\x04pong\x18\x02 \x01(\v2\x1b.notify_relay.v1.HealthPongH\x00R\x04pong\x12D\n" +
	"\vclient_list\x18\x03 \x01(\v2!.notify_relay.v1.ClientListUpdateH\x00R\n" +
	"clientListB\t\n" +
	"\amessage2\x86\x04\n" +
	"\fRelayService\x12N\n" +
	"\x06Notify\x12\x1d.notify_relay.v1.Notification\x1a%.notify_relay.v1.NotificationResponse\x12R\n" +
	"\x11CloseNotification\x12\x1d.notify_relay.v1.CloseRequest\x1a\x1e.notify_relay.v1.CloseResponse\x12^\n" +
	"\x0fGetCapabilities\x12$.notify_relay.v1.CapabilitiesRequest\x1a%.notify_relay.v1.CapabilitiesResponse\x12X\n" +
	"\rGetServerInfo\x12\".notify_relay.v1.ServerInfoRequest\x1a#.notify_relay.v1.ServerInfoResponse\x12I\n" +
	"\x06Health\x12\x1e.notify_relay.v1.HealthRequest\x1a\x1f.notify_relay.v1.HealthResponse\x12M\n" +
	"\aConnect\x12\x1e.notify_relay.v1.ClientMessage\x1a\x1e.notify_relay.v1.ServerMessage(\x010\x01B\xc9\x01\n" +
	"\x13com.notify_relay.v1B\n" +
	"RelayProtoP\x01ZMgithub.com/xtruder/notify-relay/internal/proto/notify_relay/v1;notify_relayv1\xa2\x02\x03NXX\xaa\x02\x0eNotifyRelay.V1\xca\x02\x0eNotifyRelay\\V1\xe2\x02\x1aNotifyRelay\\V1\\GPBMetadata\xea\x02\x0fNotifyRelay::V1b\x06proto3"

var (
	file_proto_notify_relay_v1_relay_proto_rawDescOnce sync.Once
	file_proto_notify_relay_v1_relay_proto_rawDescData []byte
)

func file_proto_notify_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_proto_notify_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_proto_notify_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notify_relay_v1_relay_proto_rawDesc), len(file_proto_notify_relay_v1_relay_proto_rawDesc)))
	})
	return file_proto_notify_relay_v1_relay_proto_rawDescData
}

var file_proto_notify_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_notify_relay_v1_relay_proto_goTypes = []any{
	(*Notification)(nil),          // 0: notify_relay.v1.Notification
	(*NotificationResponse)(nil),  // 1: notify_relay.v1.NotificationResponse
	(*CloseRequest)(nil),          // 2: notify_relay.v1.CloseRequest
	(*CloseResponse)(nil),         // 3: notify_relay.v1.CloseResponse
	(*CapabilitiesRequest)(nil),   // 4: notify_relay.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),  // 5: notify_relay.v1.CapabilitiesResponse
	(*ServerInfoRequest)(nil),     // 6: notify_relay.v1.ServerInfoRequest
	(*ServerInfoResponse)(nil),    // 7: notify_relay.v1.ServerInfoResponse
	(*HealthRequest)(nil),         // 8: notify_relay.v1.HealthRequest
	(*HealthResponse)(nil),        // 9: notify_relay.v1.HealthResponse
	(*LockStateUpdate)(nil),       // 10: notify_relay.v1.LockStateUpdate
	(*HealthPing)(nil),            // 11: notify_relay.v1.HealthPing
	(*HealthPong)(nil),            // 12: notify_relay.v1.HealthPong
	(*ForwardedNotification)(nil), // 13: notify_relay.v1.ForwardedNotification
	(*ClientListUpdate)(nil),      // 14: notify_relay.v1.ClientListUpdate
	(*RemoteClient)(nil),          // 15: notify_relay.v1.RemoteClient
	(*ClientMessage)(nil),         // 16: notify_relay.v1.ClientMessage
	(*ServerMessage)(nil),         // 17: notify_relay.v1.ServerMessage
	nil,                           // 18: notify_relay.v1.Notification.HintsEntry
}
var file_proto_notify_relay_v1_relay_proto_depIdxs = []int32{
	18, // 0: notify_relay.v1.Notification.hints:type_name -> notify_relay.v1.Notification.HintsEntry
	0,  // 1: notify_relay.v1.ForwardedNotification.notification:type_name -> notify_relay.v1.Notification
	15, // 2: notify_relay.v1.ClientListUpdate.clients:type_name -> notify_relay.v1.RemoteClient
	10, // 3: notify_relay.v1.ClientMessage.lock_state:type_name -> notify_relay.v1.LockStateUpdate
	11, // 4: notify_relay.v1.ClientMessage.ping:type_name -> notify_relay.v1.HealthPing
	1,  // 5: notify_relay.v1.ClientMessage.response:type_name -> notify_relay.v1.NotificationResponse
	13, // 6: notify_relay.v1.ServerMessage.notification:type_name -> notify_relay.v1.ForwardedNotification
	12, // 7: notify_relay.v1.ServerMessage.pong:type_name -> notify_relay.v1.HealthPong
	14, // 8: notify_relay.v1.ServerMessage.client_list:type_name -> notify_relay.v1.ClientListUpdate
	0,  // 9: notify_relay.v1.RelayService.Notify:input_type -> notify_relay.v1.Notification
	2,  // 10: notify_relay.v1.RelayService.CloseNotification:input_type -> notify_relay.v1.CloseRequest
	4,  // 11: notify_relay.v1.RelayService.GetCapabilities:input_type -> notify_relay.v1.CapabilitiesRequest
	6,  // 12: notify_relay.v1.RelayService.GetServerInfo:input_type -> notify_relay.v1.ServerInfoRequest
	8,  // 13: notify_relay.v1.RelayService.Health:input_type -> notify_relay.v1.HealthRequest
	16, // 14: notify_relay.v1.RelayService.Connect:input_type -> notify_relay.v1.ClientMessage
	1,  // 15: notify_relay.v1.RelayService.Notify:output_type -> notify_relay.v1.NotificationResponse
	3,  // 16: notify_relay.v1.RelayService.CloseNotification:output_type -> notify_relay.v1.CloseResponse
	5,  // 17: notify_relay.v1.RelayService.GetCapabilities:output_type -> notify_relay.v1.CapabilitiesResponse
	7,  // 18: notify_relay.v1.RelayService.GetServerInfo:output_type -> notify_relay.v1.ServerInfoResponse
	9,  // 19: notify_relay.v1.RelayService.Health:output_type -> notify_relay.v1.HealthResponse
	17, // 20: notify_relay.v1.RelayService.Connect:output_type -> notify_relay.v1.ServerMessage
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_notify_relay_v1_relay_proto_init() }
func file_proto_notify_relay_v1_relay_proto_init() {
	if File_proto_notify_relay_v1_relay_proto != nil {
		return
	}
	file_proto_notify_relay_v1_relay_proto_msgTypes[16].OneofWrappers = []any{
		(*ClientMessage_LockState)(nil),
		(*ClientMessage_Ping)(nil),
		(*ClientMessage_Response)(nil),
	}
	file_proto_notify_relay_v1_relay_proto_msgTypes[17].OneofWrappers = []any{
		(*ServerMessage_Notification)(nil),
		(*ServerMessage_Pong)(nil),
		(*ServerMessage_ClientList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notify_relay_v1_relay_proto_rawDesc), len(file_proto_notify_relay_v1_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notify_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_proto_notify_relay_v1_relay_proto_depIdxs,
		MessageInfos:      file_proto_notify_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_proto_notify_relay_v1_relay_proto = out.File
	file_proto_notify_relay_v1_relay_proto_goTypes = nil
	file_proto_notify_relay_v1_relay_proto_depIdxs = nil
}
